options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/<GCP Project Name>/<Docker Container Name>', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/<GCP Project Name>/<Docker Container Name>']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '<GCP Service Name>',
        '--allow-unauthenticated',
        '--service-account',
        '<GCP Service Account Name>@<GCP Project Name>.iam.gserviceaccount.com',
        '--image',
        'gcr.io/<GCP Project Name>/<Docker Container Name>',
        '--region',
        'europe-west1',
        '--allow-unauthenticated',
        '--max-instances',
        '30',
        '--min-instances',
        '0',
        '--memory',
        '512Mi',
        '--concurrency',
        '80',
      ]
images:
  - gcr.io/<GCP Project Name>/<Docker Container Name>
